# PROJECT:     LibreNT
# LICENSE:     BSD-3-Clause (https://spdx.org/licenses/BSD-3-Clause)
# PURPOSE:     Project configuration file
# COPYRIGHT:   Copyright 2026 Panoc95

tools:
    shell:
        allow:
            - ls *
            - echo *
            - find *
            - head *
            - mkdir *
            - cd *
            - cargo check
            - cargo search *
            - tail *
            - cargo build *
            - sleep 15
            - sleep 30
            - sleep 45
            - /home/oaky/Projects/LibreNT/target/release/libreplatformbuilder *
paths:
    allow:
        - path: /home/oaky/Projects/LibreNT/**
        - path: /home/oaky/Projects/LibreNT/utils/libreplatformbuilder/**
          write: true
