# PROJECT:     LibreNT
# LICENSE:     BSD-3-Clause (https://spdx.org/licenses/BSD-3-Clause)
# PURPOSE:     Project configuration file
# COPYRIGHT:   Copyright 2026 Panoc95

[toolchain]
channel = "stable"
components = ["rust-src", "rustfmt", "clippy"]
