# PROJECT:     LibreNT
# LICENSE:     BSD-3-Clause (https://spdx.org/licenses/BSD-3-Clause)
# PURPOSE:     Project configuration file
# COPYRIGHT:   Copyright 2026 Panoc95

tools:
    shell:
        allow:
            - mkdir *
            - ls *
            - cat *
            - echo *
            - cp *
            - find *
            - sort
            - head *
paths:
    allow:
        - path: /home/oaky/Projects/LibreNT/adk/ossetup/**
          write: true
        - path: /home/oaky/Projects/LibreNT/**
          write: true
