# PROJECT:     LibreNT
# LICENSE:     BSD-3-Clause (https://spdx.org/licenses/BSD-3-Clause)
# PURPOSE:     Project configuration file
# COPYRIGHT:   Copyright 2026 Panoc95

[build]
target-dir = "target"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-gnu]
linker = "i686-w64-mingw32-gcc"
ar = "i686-w64-mingw32-gcc-ar"
rustflags = ["-C", "target-feature=+crt-static"]

# Registry sources
[registries.crates-io]
protocol = "sparse"
