# PROJECT:     LibreNT
# LICENSE:     BSD-3-Clause (https://spdx.org/licenses/BSD-3-Clause)
# PURPOSE:     Project configuration file
# COPYRIGHT:   Copyright 2026 Panoc95

name: Build LibreNT.Shell

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        working-directory: mswindows/shell
        run: dotnet restore

      - name: Build and Package App (MSIX)
        working-directory: mswindows/shell
        run: |
          msbuild LibreNT.Shell.csproj `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:UapAppxPackageBuildMode=SideloadOnly `
            /p:AppxBundle=Never `
            /p:AppxPackageSigningEnabled=false

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WinUI3-App-Package
          path: mswindows/shell/AppPackages/
